### ISSUE TITLE
WoW 10.0 - LUA errors

### ISSUE THREAD

**Issue by Voxxel** [Choonster-WoW-AddOns/YarkoCooldowns#2]
I've read you're not willing to update this addon because of OmniCC, but this is not the same thing, YarkoCooldowns are unique and far superior than OmniCC at least in the counter displaying style. Due to it's unique color switching method close to the cooldown's expiration time this addon is still a must for me. It's catching the eyes immediately unlike OmniCC's cooldown counter.

In 10.0 there are some single line LUA errors however:

`1x Interface/AddOns/Cooldowns/Cooldowns_Options.xml:712 Unrecognized XML: OnLoad`
`1x Interface/AddOns/Cooldowns/Cooldowns_Options.xml:873 Unrecognized XML: Backdrop`
`1x Interface/AddOns/Cooldowns/Cooldowns_Options.xml:873 Unrecognized XML attribute: bgFile`
`1x Interface/AddOns/Cooldowns/Cooldowns_Options.xml:873 Unrecognized XML attribute: edgeFile`
`1x Interface/AddOns/Cooldowns/Cooldowns_Options.xml:873 Unrecognized XML attribute: tile`
`1x Interface/AddOns/Cooldowns/Cooldowns_Options.xml:874 Unrecognized XML: BackgroundInsets`
`1x Interface/AddOns/Cooldowns/Cooldowns_Options.xml:875 Unrecognized XML: AbsInset`
`1x Interface/AddOns/Cooldowns/Cooldowns_Options.xml:875 Unrecognized XML attribute: left`
`1x Interface/AddOns/Cooldowns/Cooldowns_Options.xml:875 Unrecognized XML attribute: right`

The addon is working anyway - with the display bug I reported in the other issue.

**Comment by Choonster** [comment]
I've just released 4.5, which fixes these errors.
